import type { Track } from '../music/database.js'
import { slugify, truncate } from '../../utils/text.js'

const MARKDOWN_SPECIALS = /([\\`*_{}[\]()#+!|<>~^=])/g

function escapeMarkdown(value: string): string {
  return value
    .replace(/\s+/g, ' ')
    .trim()
    .replace(MARKDOWN_SPECIALS, '\\$1')
    .replace(/@/g, '@\u200b')
}

function code(value: string): string {
  return `\`${value.replace(/[`\r\n]/g, '')}\``
}

export function buildBranchName(style: string, trackId: string): string {
  return `submissions/${slugify(style, 'style')}-${trackId.slice(0, 12)}`
}

export function buildCommitMessage(track: Track, replace = false): string {
  const verb = replace ? 'replace' : 'add'
  return `data: ${verb} ${track.style} classification for ${slugify(track.fileName, 'track')} (${track.id.slice(0, 12)})`
}

export function buildPullRequestTitle(track: Track): string {
  const label = track.title ?? track.fileName
  return `Music DB: ${track.style} - ${truncate(escapeMarkdown(label), 80)}`
}

export interface PullRequestBodyParams {
  readonly track: Track
  readonly confidence: number
  readonly branch: string
}

export function buildPullRequestBody(params: PullRequestBodyParams): string {
  const { track } = params
  const confidencePercent = Math.round(params.confidence * 100)

  const lines: string[] = ['## Music Classification', '', `**File:** ${code(track.fileName)}`]

  if (track.title) lines.push(`**Title:** ${escapeMarkdown(track.title)}`)
  if (track.artist) lines.push(`**Artist:** ${escapeMarkdown(track.artist)}`)
  if (track.album) lines.push(`**Album:** ${escapeMarkdown(track.album)}`)
  if (track.year !== undefined) lines.push(`**Year:** ${track.year}`)

  lines.push(
    `**Style:** ${escapeMarkdown(track.style)}`,
    `**Confidence:** ${confidencePercent}%`,
    `**Analysis engine:** OpenCode`,
    `**Track ID:** ${code(track.id)}`,
  )

  if (track.substyles && track.substyles.length > 0) {
    lines.push(`**Substyles:** ${track.substyles.map(escapeMarkdown).join(', ')}`)
  }
  if (track.tags && track.tags.length > 0) {
    lines.push(`**Tags:** ${track.tags.map(escapeMarkdown).join(', ')}`)
  }

  if (track.song) {
    const score =
      track.song.score !== undefined ? ` (match score ${Math.round(track.song.score)})` : ''
    lines.push(
      `**Song identification:** ${escapeMarkdown(track.song.title)} - ${escapeMarkdown(
        track.song.artist,
      )}${score}`,
    )
  } else {
    lines.push('**Song identification:** not identified')
  }

  if (track.hasLyrics === true) {
    lines.push(
      `**Vocals:** lyrics detected${track.lyricsLanguage ? ` (${escapeMarkdown(track.lyricsLanguage)})` : ''}`,
    )
  } else {
    lines.push('**Vocals:** instrumental or no lyrics detected')
  }

  if (track.diagnostics) {
    const parts: string[] = []
    if (track.diagnostics.bpm !== undefined) parts.push(`BPM ${track.diagnostics.bpm}`)
    if (track.diagnostics.key) parts.push(`key ${escapeMarkdown(track.diagnostics.key)}`)
    if (track.diagnostics.energy !== undefined) parts.push(`energy ${track.diagnostics.energy}`)
    if (parts.length > 0) lines.push(`**Diagnostics:** ${parts.join(', ')}`)
  }

  lines.push(
    '',
    `**Branch:** ${code(params.branch)}`,
    '',
    'This Pull Request was automatically generated by the public AI Music Classification system.',
    '',
    'The original audio file is not included in this repository. Full lyrics are never stored, only a flag indicating that vocals were detected.',
  )

  return `${lines.join('\n')}\n`
}

export function feedbackMarker(trackId: string): string {
  return `<!-- music-ai-feedback:${trackId} -->`
}

export interface FeedbackCommentParams {
  readonly trackId: string
  readonly song?: { readonly title: string; readonly artist: string }
}

export function buildFeedbackComment(params: FeedbackCommentParams, confirmed: boolean): string {
  const verdict = confirmed
    ? 'confirmed the detected song match as **correct**'
    : 'reported the detected song match as **incorrect**'

  const lines = [
    feedbackMarker(params.trackId),
    '### Submitter feedback',
    '',
    `An anonymous submitter ${verdict}.`,
  ]

  if (params.song) {
    lines.push(
      '',
      `Detected song: ${escapeMarkdown(params.song.title)} - ${escapeMarkdown(params.song.artist)}`,
    )
  }

  lines.push('', `_Track ID: ${code(params.trackId)}_`)
  return lines.join('\n')
}
